
## Custome default values for testing ##

name: "Mohit"
home: "NewDelhi"

# below is anoter set of data 

projectCode: aazzxxyy
infra:
  zone: a,b,c
  region: us-e

  # data to practice with scope 
 
tags:
   machine: frontdrive
   rack: 4c
   drive: ssd
   vcard: 8g


   #Looping with Range used in configmap
  
LangUsed:
   - Python
   - Ruby
   - Java
   - Scala

