---
installCRDs: true
prometheus:
  enabled: false
  servicemonitor:
    enabled: false
    prometheusInstance: lesson-083
# DNS-01 Route53
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::833192599359:role/cert-manager-acme
extraArgs: 
  - --issuer-ambient-credentials
